databases:
  - name: stockx-clone-db
    plan: free

services:
  - type: web
    name: stockx-clone
    runtime: node
    plan: free
    buildCommand: cd client && npm install --include=dev && npx vite build && cd ../server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: stockx-clone-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
